.github/ci-hpc-config.yml
CHANGELOG.md

adds missing ci-hpc-config.yml

ci: add hpc-config

---

src/anemoi/inference/runner.py

Add verbosity flag to runner to control printing of summary

Add verbosity to runner

---

docs/conf.py
pyproject.toml
src/anemoi/inference/__init__.py
src/anemoi/inference/__main__.py
src/anemoi/inference/checkpoint/__init__.py
src/anemoi/inference/checkpoint/metadata/__init__.py
src/anemoi/inference/commands/__init__.py

----
📚 Documentation preview 📚: https://anemoi-inference--41.org.readthedocs.build/en/41/

missing copyrigths

---

docs/configs/top-level.rst
src/anemoi/inference/config.py

----
📚 Documentation preview 📚: https://anemoi-inference--66.org.readthedocs.build/en/66/

Make write_initial_state default to true

---

src/anemoi/inference/runner.py

Do not compute next-step forcing if current step is the last one

---

src/anemoi/inference/checkpoint.py
src/anemoi/inference/config.py

Hotfix: huggingface loading issues (#81)

---

.github/workflows/python-pull-request.yml
pyproject.toml
src/anemoi/inference/checkpoint.py
src/anemoi/inference/config.py
tests/checkpoint/test_huggingface.py
tests/metadata/fake_metadata.py

Tests huggingface download

---

.github/workflows/python-pull-request.yml
src/anemoi/inference/checkpoint.py
src/anemoi/inference/config.py
src/anemoi/inference/metadata.py
src/anemoi/inference/provenance.py
src/anemoi/inference/state.py

Previous attempt failed due to broken tests on python 3.9

The real release 0.4.4

---

src/anemoi/inference/commands/requests.py
src/anemoi/inference/commands/run.py
src/anemoi/inference/commands/sanitise.py
src/anemoi/inference/commands/validate.py

Fix typo in sanitise and update the help string of the commands.

chore: commands vocabulary and help

---

.github/workflows/python-publish.yml

ci: remove checks from pypi publish

---

src/anemoi/inference/checkpoint.py
src/anemoi/inference/commands/retrieve.py

Retrieve from `stream=scda` for input start time 0600/1800

feat(retrieve): Add `--use-scda` flag

---

src/anemoi/inference/commands/requests.py
src/anemoi/inference/commands/retrieve.py

-   [ x] Bug fix (non-breaking change which fixes an issue) …

fix: issue #127, command "requests" broken

---

src/anemoi/inference/outputs/printer.py

If `names` has length <n you get a ValueError.
I decided to push this instead of an issue.
- …

fix: Update output: printer to avoid range(a, b, 0)

---

docs/configs/outputs.rst
docs/configs/outputs_9.yaml
src/anemoi/inference/outputs/netcdf.py
src/anemoi/inference/outputs/truth.py

Add a truth output, which writes the truth from the input at the same time.
-   [x] New feature (non-breaking change which adds functionality)
-   [x] I have ensured that the code is still pip-installable after the changes and runs
-   [x] I have tested that new dependencies themselves are pip-installable.
-   [x] My code …

feat: Add truth output

---

src/anemoi/inference/commands/retrieve.py

fix: prepml staging

---

docs/cli/validate.rst
docs/index.rst
pyproject.toml

Improve validate docs
----
📚 Documentation preview 📚: https://anemoi-inference--151.org.readthedocs.build/en/151/

docs: Add validation info

---

pyproject.toml

fix: fix pyproject.toml

---

src/anemoi/inference/outputs/grib.py

fix: unused parameter

---

src/anemoi/inference/outputs/grib.py

Fix grib output

---

src/anemoi/inference/provenance.py
src/anemoi/inference/runner.py

fix: better error messages

---

src/anemoi/inference/grib/templates/manager.py

Add `area` to template lookup dictionary.

fix: Add area to template lookup dictionary

---

src/anemoi/inference/runner.py

Alter model load failure warning to be less helpful and not hide the true error

fix: Be less helpful

---

pyproject.toml

chore: update anemoi-utils dependency version

---

pyproject.toml

Missed this in #301...
Makes versions in pyproject.toml consistent
n/a
n/a

chore: Consistent anemoi-utils versions in pyproject.toml

---

src/anemoi/inference/runner.py

Bug appears when running parallel

fix: device type in autocast

---

src/anemoi/inference/runner.py

replaces torch.no_grad with torch.inference_mode
1/ should gain even more speedup as version tracking / counters, cf https://docs.pytorch.org/docs/2.8/generated/torch.autograd.grad_mode.inference_mode.html . Note this additionally disables AD in forward mode, but I guess this is not being used anywhere
2/ replacet the set call with context managers, to not pollute the global state

feat: replace no grad with inference mode

---

src/anemoi/inference/inputs/cutout.py

The recent PR #262 broke the cutout input

fix: Update cutout due to #262
