ecmwf/anemoi-inference

- CHANGELOG.md
- pyproject.toml
- src/anemoi/inference/runner.py
- Replaces climetlab with earthkit
- Added to CHANGELOG
- Adjusted `pyproject.toml`
Closes #7
> Fix: Remove climetlab to be replaced by earthkit

- src/anemoi/inference/runner.py
Dear Baudouin,
I have been experiencing difficulties with my manually crafted GRIB input, specifically related to the datetime information within the metadata. To save myself from the same issue in the future, I believe it would be useful to verify the timestamps of the input data. However, I do not yet have a comprehensive understanding of the inference code, so please feel free to suggest another way to validate the input data.
Best,
Marek
> Check valid_datetime of input data

- CHANGELOG.md
- pyproject.toml
- src/anemoi/inference/condition.py
- tests/test_condition.py
- Stores data as a dictionary
- Can be made from xarray, earthkit, numpy, or dict
- Can be exported to array
Closes #16
> Feature: Add Condition

- CHANGELOG.md
- src/anemoi/inference/checkpoint/metadata/version_0_2_0.py
- src/anemoi/inference/runner.py
Inference failed when no constant forcings were used in the training.
The error message related to the fact, that an empty list in `computed_forcing_mask` can't be used as an index.
> Enable inference when no constant forcings are used

- .github/workflows/python-publish.yml
- .github/workflows/python-pull-request.yml
- CHANGELOG.md
- src/anemoi/inference/checkpoint/__init__.py
- src/anemoi/inference/checkpoint/metadata/version_0_0_0.py
- src/anemoi/inference/checkpoint/metadata/version_0_1_0.py
- src/anemoi/inference/checkpoint/metadata/version_0_2_0.py
This PR extends the python versions of the PR and publish workflows.
> ci: extend python versions

- src/anemoi/inference/commands/run.py
In run.py GribFileInput was called with one `context` argument too much.
This PR fixes that.
> fix duplicate argument

- src/anemoi/inference/inputs/dataset.py
The calling of the dataset path was broken, since .zarr was stripped. Furthermore it is more convenient to keep the full dataset path as set in the checkpoint as the default. In the fix here the path as read from the checkpoint is directly fed to anemoi-datasets `open_dataset`.
> fix dataset path

- src/anemoi/inference/commands/run.py
- src/anemoi/inference/config.py
- src/anemoi/inference/outputs/raw.py
Basic output, saving the dictionary with numpy arrays as .npz, should work for all input types. Raw output is turned on by setting `output_type: raw` in the config, in that case `output: path` sets the directory where the output will be stored. If `output_type` is not set in the config, but `output` is specified, grib output is assumed, as to be backwards compatible.
Example config:
output: first-experiment
output_type: raw
checkpoint: inference-last.ckpt
date: 2007-10-03
dataset: True
lead_time: 6h
> add raw output

- CHANGELOG.md
- src/anemoi/inference/runner.py
Not quite a bugfix or a feature, just a little change which can save some memory
```python
- prognostic_fields = y_pred[..., prognostic_output_mask]
...
- input_tensor_torch[:, -1, :, prognostic_input_mask] = prognostic_fields
+ input_tensor_torch[:, -1, :, prognostic_input_mask] = y_pred[..., prognostic_output_mask]
```
Currently we create a `prognostic_fields` variable and then assign it to `input_tensor_torch` a few lines later. Nothing happens to `prognostic_fields` or `y_pred` in-between, so i guess this variable is just for readability? 
The issue is this prog fields memory is never freed, so, after the first iteration we carry around this `prognostic_fields` variable. At 9km resolution, this is 2.2GB of memory (~3% of an H100s memory). We can save this memory by removing the …
> remove prog fields variable

- CHANGELOG.md
- docs/configs/top-level.rst
- src/anemoi/inference/config.py
- src/anemoi/inference/output.py
- src/anemoi/inference/outputs/netcdf.py
- src/anemoi/inference/outputs/plot.py
- src/anemoi/inference/outputs/raw.py
This PR closes #61 and #48. 
A new function `reduce()` is added to the `Output` class, which projects a state to the last step in the multi-step dimension.
This function is then used to define `write_initial_state()` as a combination of `reduce()` and `write_state()` for the netcdf, raw and plot output.
The naming of the raw output is brought in line with the naming of the plot output.
The default `write_initial_state` config setting is now `true`.
----
📚 Documentation preview 📚: https://anemoi-inference--62.org.readthedocs.build/en/62/
> Improved output of initial state

- src/anemoi/inference/metadata.py
Replaces frozendict implementation by existing stdlib thing which behaves more or less the same, but coops with pickle
I've tested like `d = frozendict({'a': 4})` and `d['a'] == 4` and `d['a'] = 5 # raises` and `del d['a'] # raises` and `d['b'] = 7 # raises`. Are there any other cases of interest?
(ftr I put `no changelog` here, this should have no outwardly visible effect)
> Make frozendict picklable

- CHANGELOG.md
- docs/configs/top-level.rst
- pyproject.toml
- src/anemoi/inference/checkpoint.py
- src/anemoi/inference/config.py
Models will be downloaded from huggingface through specification in the config.
```yaml
checkpoint:
huggingface:
repo_id: "ecmwf/aifs-single"
filename: "aifs_single_v0.2.1.ckpt"
```
----
📚 Documentation preview 📚: https://anemoi-inference--75.org.readthedocs.build/en/75/
> Add support for downloading models from huggingface

- src/anemoi/inference/outputs/gribfile.py
Ouput the archive json with no indent by default, so it is only on 1 line. This makes it easier to handle the file afterwards, like concat into a jsonl file.
> Output archive requests json with no indent by default

- src/anemoi/inference/outputs/raw.py
Ensure that coordinates are written to raw output as floats instead of strings as it currently happens.
> Write output coordinates of RawOutput as floats

- src/anemoi/inference/checkpoint.py
- src/anemoi/inference/metadata.py
- src/anemoi/inference/outputs/gribfile.py
- src/anemoi/inference/outputs/raw.py
> Release 0.4.2

- CHANGELOG.md
- src/anemoi/inference/checkpoint.py
- src/anemoi/inference/forcings.py
- src/anemoi/inference/inputs/dataset.py
- src/anemoi/inference/metadata.py
This PR adds support for inference from checkpoints created with models where unconnected nodes have been dropped from the input grid, see [anemoi-training #171](https://github.com/ecmwf/anemoi-training/pull/171). For the moment the functionality is restricted to inference taking an anemoi-dataset as input.
The indices of those gridpoints in the dataset that remain as input for the model are stored in the checkpoint as the supporting array `grid_indices`.  The current implementation is such that if this supporting array is present in the checkpoint then the input is automatically reduced to those points with indices listed in `grid_indices`. 
A small update of the boundary forcing is also needed, the mask used is now (the negation of) the `output_mask` that can be found in relevant …
> Support models with unconnected nodes removed from input (LAM)

- src/anemoi/inference/outputs/netcdf.py
> Fix netcdf output

- .github/workflows/python-pull-request.yml
- src/anemoi/inference/checkpoint.py
- src/anemoi/inference/config.py
- src/anemoi/inference/metadata.py
- src/anemoi/inference/provenance.py
- src/anemoi/inference/state.py
- Turn on python 3.9 in the QA version matrix
- `type | None` is unsupported  in python 3.9, replace it with `Optional[type]` or `Union[type, type, None]`
Other instances of `|` do work thanks to `__future__.annotations` , so I left those alone.
> Turn on python 3.9 QA and fix typing

- src/anemoi/inference/commands/run.py
- src/anemoi/inference/config.py
- src/anemoi/inference/runner.py
- src/anemoi/inference/runners/__init__.py
- src/anemoi/inference/runners/crps.py
To support running the CRPS model, which has an extra argument `fcstep` in the `predict_step` fn. This argument is only picked up by the new `CrpsRunner`, and ignored by default.
Any other future extra arguments can be passed in this way, and only used by a specific runner.
> Instantiate runner from config and add CRPS runner

- src/anemoi/inference/checkpoint.py
- src/anemoi/inference/metadata.py
- src/anemoi/inference/outputs/extract_lam.py
> fix: extract_lam output

- CHANGELOG.md
- src/anemoi/inference/commands/run.py
- src/anemoi/inference/config.py
- src/anemoi/inference/context.py
- src/anemoi/inference/output.py
- src/anemoi/inference/outputs/__init__.py
- src/anemoi/inference/outputs/apply_mask.py
- src/anemoi/inference/outputs/extract_lam.py
- src/anemoi/inference/outputs/grib.py
- src/anemoi/inference/outputs/gribfile.py
- src/anemoi/inference/outputs/netcdf.py
- src/anemoi/inference/outputs/none.py
- src/anemoi/inference/outputs/plot.py
- src/anemoi/inference/outputs/printer.py
- src/anemoi/inference/outputs/raw.py
- src/anemoi/inference/outputs/tee.py
- src/anemoi/inference/runner.py
- src/anemoi/inference/runners/default.py
Allow users to write only certain steps. The frequency can be set globally or per output.
> feat: Add support for `output_frequency` to write less output

- src/anemoi/inference/commands/retrieve.py
If the config contains an input grib, the retrieve command will use that are the target in the generated mars request. 
Also make the default output stdout.
config.yaml:
```yaml
input:
grib: input.grib
checkpoint: model.ckpt
```
```
anemoi-inference retrieve config.yaml --date 20240101T00:00:00
```
will have target=input.grib
Target can still be overwritten by passing `--extra target=anotherinput.grib`
> feat(retrieve): Use input grib as target

- src/anemoi/inference/config.py
- src/anemoi/inference/runner.py
- src/anemoi/inference/runners/default.py
Implements step 1 and 2 of #131 
For CLI and OO API users: if `post_processors` is not defined in the user-config, the current behaviour is to keep accumulating from the beginning of the forecast. A warning is shown to alert users that this will change in the future.
To explicitly turn accumulations from beginning of the forecast on or off, the user can do:
```yaml
post_processors: 
- accumulate_from_start_of_forecast
```
```yaml
post_processors: []
```
For the numpy-to-numpy API  it is turned off by default.
> feat(config): Add `accumulate_from_start_of_forecast` post-processor

- src/anemoi/inference/runner.py
- src/anemoi/inference/runners/default.py
Forgot this in #133
Linked to #131
> refactor: Rename `accumulations` -> `accumulate_from_start_of_forecast`

- CHANGELOG.md
- docs/parallel.rst
- src/anemoi/inference/commands/run.py
- src/anemoi/inference/config.py
- src/anemoi/inference/runners/__init__.py
- src/anemoi/inference/runners/parallel.py
This PR extends the Parallel Inference added in #55 to work without slurm **within 1 node**. It's much nicer to debug and run now :D
When running parallel inference without slurm, you have to add `world_size` to the config. At the moment, this is ignored in favour of `SLURM_NTASKS` when running with srun. An example of a config running parallel inference across 4 nodes is shown below. You can launch this job as normal with `anemoi-inference run parinf.yaml`.
```yaml
checkpoint: /path/to/inference-last.ckpt
lead_time: 60
runner: parallel
world_size: 4 #Only required if running parallel inference without Slurm
input:
grib: /path/to/input.grib
output:
grib: /path/to/output.grib
```
How it works is:
- check if anemoi-inference is launched by srun
- if not, spawn `config.world_size` processes …
> feat: parallel inference without slurm

- src/anemoi/inference/outputs/grib.py
- src/anemoi/inference/outputs/gribfile.py
Allow users to specify a list of variables (a subset of the variables in the state fields) that they want to include in an output GRIB file. 
- added a `variable` keyword to the corresponding classes. When not provided, all fields are written to output. 
- also made a bugfix on L262 of `grib.py` so it uses the correct param (based on the original local definitions used when creating the anemoi dataset), e.g. in our case `T_2M` would need to be used instead of `2t`.
> feat(output): allow selecting variables for GRIB output

- src/anemoi/inference/commands/retrieve.py
The `retrieve` command still has the runner hardcoded. Update this to also support custom runners in the config.
> feat(retrieve): Create runner from config

- src/anemoi/inference/profiler.py
- src/anemoi/inference/runner.py
some small fixes to the profiler
- fix a bug where only the input state preprocessing was being profiled
- removed memory_timeline.html bc its slow to generate and the memory pickle shows the same info but better
- change where the profile output is written to, so new runs dont overwrite old ones
- add more log output to explain how to view profiler output
- remove saving the stack trace from pytorch profiler, otherwise the trace files couldnt be opened
> fix: Update Profiler

- src/anemoi/inference/runner.py
- src/anemoi/inference/runners/default.py
- Fixes a crash that happens when post_processors is not defined in the config. 
- Remove leftover temporary code from before we had a processor factory.
Related to #131 , the logic that facilitates the transition to not accumulating by default was broken. 
> fix: Post processors

- src/anemoi/inference/grib/encoding.py
- src/anemoi/inference/metadata.py
- src/anemoi/inference/outputs/grib.py
The checkpoint variables metadata might contain an `hdate` key in the data request, if the model was trained on hindcast data.
This key needs to be skipped when constructing the initial condition request and writing to grib. 
> fix: Remove `hdate` from variable keys

- src/anemoi/inference/outputs/gribfile.py
When requesting output of parameter ids instead of short codes we got an error if we already had param ids in the request. This adds a check to see what we have an skips the lookup step.
> fix: param id handling at archive JSON output

- src/anemoi/inference/outputs/grib.py
The list of "forbidden keys" that should be skipped when building the output keys now lives in [grib_keys()](https://github.com/ecmwf/anemoi-inference/blob/9313155e7bc19b0fce51f6330c98761343ccfb54/src/anemoi/inference/grib/encoding.py#L281). 
So it can be removed here.
> fix(grib): Remove duplicate grib key logic

- src/anemoi/inference/inputs/ekd.py
Adds a check if the date is None with the earthkit-data GRIB input.
> fix: Add check for date is None with earthkit-data GRIB input

- src/anemoi/inference/outputs/netcdf.py
- src/anemoi/inference/runner.py
- src/anemoi/inference/runners/default.py
Two bugs:
1. The netcdf output uses the context attributes `self.lead_time` and `self.time_step` in the `open` routine, which is called before these attributes are set.
2. `NetCDFOutput.open` reads reference_date from the context, but doesn't check if the value is not None. 
- Set the context attributes `self.lead_time` and `self.time_step` at the beginning of execute, before they are accessed.
- Check if the context reference_date is not None, otherwise use the date from the state.
> fix(netcdf): Fix context time attributes

- src/anemoi/inference/testing/__init__.py
Add `functools.wraps` to decorator to allow usage of `pytest.marks` in downstream tests.
```python
@pytest.mark.parametrize(
"arg1, arg2",
[
("wow", 'test'),
],
)
@fake_checkpoints
def test(arg1, arg2):
assert arg1 != arg2
```
> fix: Improve Testing Decorators

- src/anemoi/inference/outputs/extract_lam.py
Extract lam output reduces the output to that of the lam region, which is defined by the `cutout_mask` as stored in the checkpoint. The correct supporting array is `0/lam_0/cutout_mask`, in the code it was erroneously referenced as  `lam_0/cutout_mask`. This typo is fixed.
Closes #86 
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [ ] I ran the [complete Pytest test](https://anemoi.readthedocs.io/projects/training/en/latest/dev/testing.html) …
> fix: extract-lam

- src/anemoi/inference/runner.py
- src/anemoi/inference/runners/crps.py
The problem is described in https://github.com/ecmwf/anemoi-core/pull/277. The forward function of `AnemoiEnsModelEncProcDec` takes additional arguments that need to be passed from anemoi-inference.
> fix: Inference with crps requires additional arguments in predict_step

- src/anemoi/inference/testing/__init__.py
- src/anemoi/inference/testing/mock_checkpoint.py
Mocking checkpoints didn't allow for downstream tests to mock metadata
> fix: Allow for downstream tests to provide checkpoint mocks

- src/anemoi/inference/metadata.py
After forcings were refactored `boundary_forcings_inputs` was returning a list of lists, rather than a list, in the non trivial case where the checkpoint contains the `output_mask` supporting array. This PR fixes this.
-   [x] I have ensured that the code is …
> fix: boundary forcings inputs

- src/anemoi/inference/commands/metadata.py
- Add code --wait
Allows for vscode to be used in the metadata command.
`anemoi-inference metadata --edit CHECKPOINT --editor code`
-   [x] New feature (non-breaking change which adds functionality)
-   [x] I ran the [complete Pytest test](https://anemoi.readthedocs.io/projects/training/en/latest/dev/testing.html) suite locally, and they pass
-   [x] I have ensured that the code is still pip-installable after the changes and runs
-   [x] I have tested that new dependencies themselves are pip-installable.
-   [x] My code follows the style guidelines …
> feat: Add cmd options to editor

- src/anemoi/inference/grib/encoding.py
During the encoding of the `grib` output, `eccodes` raises the following error:
```
KeyValueNotFoundError: Key/value not found
```
this happens when trying to set the `eps` key. It appears that this key not universally compatible with GRIB encodings. Therefore, this PR removes the hardcoded specification. 
-   [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
> fix!: do not set 'eps' key in grib encoding

- src/anemoi/inference/runner.py
We have debug logging calls in a few places but we don't set the logger to debug level anywhere. This sets all loggers to debug level when verbosity > 2
> feat: Set debug log level on verbosity > 2

- docs/usage/external-graph.rst
- docs/usage/yaml/external-graph4.yaml
- docs/usage/yaml/external-graph5.yaml
- pyproject.toml
- src/anemoi/inference/runners/external_graph.py
Improvements being made to the external graph runner to allow the supporting arrays to be updated from the graph.
Additionally, removes anemoi-datasets as a hard dependancy.
Enables broader usage of this runner.
----
📚 Documentation preview 📚: https://anemoi-inference--247.org.readthedocs.build/en/247/
> fix: Improve external graph

- src/anemoi/inference/inputs/mars.py
Allow for `mars` logging to be turned off.
```yaml
input:
mars:
log: False
```
```python
from anemoi.inference.inputs.mars import MarsInput
MarsInput(log = False)
```
> feat: Add logging control to mars

- src/anemoi/inference/runner.py
Output tensor was not detached when printing it or writing it to a trace file, side effect of #263. 
> fix: Tensor not detached in debug mode

- pyproject.toml
- src/anemoi/inference/grib/encoding.py
- src/anemoi/inference/outputs/grib.py
- src/anemoi/inference/outputs/gribfile.py
A three-for-one grib special:
- Remove the hardcoded edition=1 for hindcasts so that we can do hindcasts with grib2-only variables, like those in the ocean. The edition comes from the template, so grib1 in will still do grib1 out. 
- Perform time encoding with the period information in the variable metadata, instead of the model's step size. This is to support fields that have different periods than the model step (like ocean averages).
- When the `accumulate_from_start_of_forecast` processor was enabled, we didn't properly set `startStep=0`, it was doing `startStep=previous_step`.
Draft for now (tests will be failing) because it needs a new release of transform after merging this:
https://github.com/ecmwf/anemoi-transform/pull/132
***As a contributor to the Anemoi framework, please …
> fix(grib): Ocean grib encoding

- pyproject.toml
- src/anemoi/inference/outputs/masked.py
- src/anemoi/inference/outputs/printer.py
- src/anemoi/inference/post_processors/extract.py
- tests/conftest.py
- tests/unit/test_post_processors.py
This PR adds two new post-processors `extract_mask` and `extract_slice` (the extraction logic is shared in a common class), which can be used to extract subsets of points from the state based on boolean masks or slices respectively. Closes #281. 
The post-processors can be used as follows:
```yaml
output:
printer:
post_processors:
- extract_slice: [0, 189700]
```
or 
```yaml
output:
printer:
post_processors:
- extract_mask: mask/in/supporting_arrays or /path/to/mask.npy
```
---
***As a contributor to the Anemoi framework, please ensure that your changes include unit tests, updates to any affected dependencies and documentation, and have been tested in a parallel setting  (i.e., with multiple GPUs). As a reviewer, you are also responsible for verifying these aspects and requesting changes …
> feat(post-processors): extraction post-processors

- src/anemoi/inference/outputs/assign_mask.py
- src/anemoi/inference/post_processors/assign.py
- src/anemoi/inference/post_processors/extract.py
- tests/conftest.py
- tests/unit/test_post_processors.py
This PR adds a new `assign_mask` post-processor that can be used to assign the arrays in the current state object to arrays of a larger size using a boolean array mask. It can be seen as the inverse of `extract_mask` introduced in #285. 
The corresponding output type is now deprecated and will be removed in a future release.
---
By opening this pull …
> feat(post-processors): add `assign_mask` post-processor

- tests/conftest.py
This PR removes --longtests cli option for pytest.
Make markers and cli for slow tests consistent across the anemoi packages.
https://github.com/ecmwf/anemoi-core/issues/257
> test: remove longtests pytest cli option

- src/anemoi/inference/commands/inspect.py
- src/anemoi/inference/metadata.py
Option for the `inspect` command to output in pure JSON, like this:
```shell
$ anemoi-inference inspect --json checkpoint.ckpt
```
This can be useful when inspecting the checkpoint programmatically, for example:
```shell
$ anemoi-inference inspect --json checkpoint.ckpt | jq '.diagnostic_variables'
[
"cp",
"tp"
]
```
By opening this pull request, I affirm …
> feat(inspect): JSON output

- src/anemoi/inference/runner.py
Fix for running inference with single variable output
When running anemoi-inference, and only predicting one single variable, the run will fail due to the "output"-variable being squeezed into a 1D array. Anemoi-infernece expect it to be 2D.
The same problem occurs when running the downscaling runner (as noted by user @paulina-t )
N/A
N/A
By opening this …
> fix: Inference with single variable
